config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'todos/index'
get 'todos/new'
post 'todos', to: 'todos#create'
get 'todos/:id', to: 'todos#show', as: 'todo'
get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
patch 'todos/:id', to: 'todos#update'
delete 'todos/:id', to: 'todos#destroy'
get 'todos/:id/complete', to:'todos#complete'
get 'todos/list'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_index_path

  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_index_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_index_path
  end

  def complete
    @todo = Todo.find(params[:id])
    :completed == True
    @todo.save
    


  end

  def list
    @todos = Todo.all
  end


private

  def todo_params
    params.require(:todo).permit(:description , :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top navbar-no-bg" role="navigation">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="">Trilli Bi - Bootstrap Landing Page</a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="top-navbar-1">
    <ul class="nav navbar-nav navbar-right">
      <li><a class="scroll-link" href="#top-content">Top</a></li>
      <li><a class="scroll-link" href="#features">Features</a></li>
      <li><a class="scroll-link" href="#screenshots">Screenshots</a></li>
      <li><a class="scroll-link" href="#pricing">Price</a></li>
      <li><a class="scroll-link" href="#testimonials">Testimonials</a></li>
      <li><a class="scroll-link" href="#about-us">About</a></li>
      <li><a class="scroll-link" href="#contact">Contact</a></li>
    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>



  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo , local: true do |f| %>
  <%= f.label :description, "description" %>
  <%= f.text_field :description %>
  <%= f.label :completed, "Completado" %>
  <%= f.check_box :completed %>
  <%= f.submit "Enviar" %>
<% end %>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<% @todos.inspect %>

<div class = "card" >
<% @todos.each do |todo| %>
<h1> <%= todo.description %> </h1>
  <p> <%= todo.completed %> </p>
  <p> <%= link_to "show", todo %> </p>
  <p> <%= link_to "edit", edit_path(todo) %> </p>
  <p> <%= link_to "borrar", todo, method: :delete %></p>
<% end %>

</div>

<%= link_to "Crear ToDo", todos_new_path %>

app/views/todos/list.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <div class="container">
      <div class="row">
        <div class="col">
          Completado
        </div>
        <div class="col">
          No Completado
        </div>
      </div>

  </body>
</html>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<%= @todo.description %>
<%= @todo.completed %> 